# Use postgres/example user/password credentials
version: '3.1'

services:
  test-db:
    image: postgres:15.3
    container_name: test-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-db
